### ISSUE TITLE
Type declarations and real object at runtime is different

### ISSUE THREAD

**Issue by progrestian** [Tenpi/deviantart.ts#5]
So I tried running a simplified version of the example code below:

```js
import DeviantArt from "deviantart.ts"
 
async function main() {
    const da = await DeviantArt.login(process.env.DA_CLIENTID, process.env.DA_SECRET)
}

main()
```

but it gives an error instead:

```
(node:11368) UnhandledPromiseRejectionWarning: TypeError: DeviantArt.login is not a function
```

So I tried to see what the real representation of `DeviantArt` looks like, which is:

```js
{
    __esModule: true,
    default: [Function: DeviantArt] { login: [Function (anonymous)] },
    Deviation: [Function: Deviation],
    Gallery: [Function: Gallery],
    RSS: [Function: RSS],
    User: [Function: User],
    Util: [Function: Util],
    Browse: [Function: Browse],
    Curated: [Function: Curated],
    Stash: [Function: Stash],
    Collections: [Function: Collections],
    Comments: [Function: Comments],
    Data: [Function: Data]
}
```

and then changed my code to:

```js
import DeviantArt from "deviantart.ts"
 
async function main() {
    const da = await DeviantArt.default.login(process.env.DA_CLIENTID, process.env.DA_SECRET)
}

main()
```

but then tsc will complain during transpilation like so:

```
index.ts:26:28 - error TS2339: Property 'default' does not exist on type 'typeof DeviantArt'.
```

The only workaround I know is to modify the transpiled function directly by hand, from `DeviantArt.login` into `DeviantArt.default.login`. Or am I doing something wrong?

**Comment by Moebytes** [comment]
Make sure that you set the `module` property in your `tsconfig.json` to `commonjs`:
`"module": "commonjs"`
And remove `"type": "module"` from `package.json` if you had it.

Let me know if you still have an issue.

**Comment by progrestian** [comment]
Ah, that fixed the problem. Thanks for the solution!
